# Site settings
title:       Nervous Systems
email:       moe@nervous.io
author:      Moe Aboulkheir
description: "A micro-consultancy specializing in functional and asynchronous programming."
baseurl:     ""
url:         "https://nervous.io"
highlighter: rouge

# Google analytics
google_analytics: UA-63587838-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: nervous-systems
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'fenced_code_blocks']
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems: [jekyll-compose]

name: Nervous Systems

